FROM python:alpine3.16 as build
WORKDIR /app
RUN mkdir /plib && cd /plib && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && apk add git && git clone https://github.com/lightnovel-center/linovelib2epub.git
RUN cd /plib && cd linovelib2epub && ls -all && ( cat src/linovelib2epub/linovel.py | sed '254,257d' | sed "254i\            os.makedirs(out_folder);" | sed "254i\        if not os.path.exists(out_folder):" | sed "254i\        out_folder = \"data\/\" + str(self.epub_settings[\"book_id\"])" | sed "s@sanitize_pathname(out_folder)@out_folder@g" > src/linovelib2epub/linovel.py ) &&  sed "s@https://w.linovelib.com/themes/zhmb/js/readtools.js@https://www.linovelib.com/themes/zhpc/js/pctheme.js@g" -i src/linovelib2epub/spider/linovelib_mobile_rules.py && python3 -m venv venv && chmod +x ./venv/bin/activate && ./venv/bin/activate && python3 -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple && python3 -m pip install -e . && pip3 install argparse -i https://mirrors.aliyun.com/pypi/simple
COPY lib.py /app/lib.py
RUN pip3 install pyinstaller -i https://mirrors.aliyun.com/pypi/simple && apk add binutils && pyinstaller lib.py && cd /app/dist/lib && cp -r /usr/local/lib/python3.11/site-packages/fake_useragent ./_internal/ && mkdir _internal/linovelib2epub && cp -r /plib/linovelib2epub/src/linovelib2epub/styles  _internal/linovelib2epub


FROM alpine
COPY --from=build /app/dist/lib /app
WORKDIR /app
ENTRYPOINT ["/app/lib"]

# -h 查看用法

# docker run -v $PWD/out:/app/data -v $PWD/temp:/app/temp 


