name: docker

on:
  push:
   branches: ['certbot']

   paths-ignore:
    - 'README.md'
  workflow_dispatch:
  
jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write

   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       with:
         ref: 'certbot'
     - name: Log in to the Container registry
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: Date Tag
       id: date
       run: |
         tag=$(date +%Y%m%d)
         echo "date_tag=$tag" >> $GITHUB_OUTPUT
     - name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@v5
       with:
         images: ghcr.io/${{ github.repository_owner }}/certbot
         tags: |
            type=sha
            type=raw,value=${{ steps.date.outputs.date_tag }}
            type=raw,value=latest,enable=true

     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
         context: .
         push: true
         file: Dockerfile
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}
         github-token: ${{ secrets.GITHUB_TOKEN }}
